### ISSUE TITLE
Fehlerhafter Freitext bei manchen verteilten Vorlagen

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/ePortfolio#245]
Manchmal taucht ein Freitextfeld mit folgendem Inhalt beim Studierenden auf:
`<?xml encoding="utf-8" ?> `

* Woher kommt das? 
* Wie kriegt man das weg?

**Comment by sschuppUOS** [comment]
Ich glaube, dass der Fehler aus der importContents-Methode des HTML-Blocks in der Courseware kommt:
In den Zeilen 206-212 wird überprüft, ob in den gegebenen Contents das utf-8 encoding zu finden ist. Wenn der Content aber z.B. leer ist und dadurch nichts in der Methode übergeben wird, wird
`<?xml encoding="utf-8" ?>` vorne an die Contents angehängt und führt somit dazu, dass nur der XML-Tag in den Contents steht.

Anscheinend führt das dazu, dass der Tag dann im kopierten HTML-Block erscheint.

**Comment by tgloeggl** [comment]
Ah, das klingt plausible. Also muss das in der Courseware gefixt werden. Ich werde da sobald ich Zeit habe einen Blick drauf werfen!

**Comment by tgloeggl** [comment]
Ist in der Portfolio-Variante der Courseware gefixt.

**Comment by julianadinewarrelmann** [comment]
Hi Till, das taucht ja nun noch immer den der rot hinterlegten Kapitel 2, das eben nicht aus einer Vorlage stammt, daher lasse ich den Punkt hier nochmal stehen, ja?
