### ISSUE TITLE
Kommunikations- und Benachrichtigungssystem

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/ePortfolio#274]
Auf der Übersichtsseite visualisieren, wo sich was geändert hat (für Dozenten)

* Regeln Rotfärbung:
    * Student
        * Es wurde eine neue Vorlage verteilt
        * Dozent hat ein Feedback gegeben
    * Dozent
        * Es gibt eine neue Freigabe von einem Studi

* Regeln Entfärbung:
    * Student
        * Hat sich im Portfolio-Arbeit-Reiter aufgehalten
    * Dozent
        * Hat sich im Portfolio-Arbeit-Reiter aufgehalten

* Rotfärbung (Sternchen-Markierung) der Freigaben im Portfolio-Arbeit-Reiter
    * Funktioniert diese korrekt?
    * Was sind die Regeln für Färbung/Entfärbung?

**Comment by sschuppUOS** [comment]
Ich gehe davon aus, dass hier die Veranstaltungsübersicht gemeint ist.
Soll sich das Icon auch verfärben wenn ein User eine SupervisorNotiz anlegt?
