### ISSUE TITLE
supervisor_id aus Tabelle eportfolio entfernen

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/ePortfolio#282]
Dieses Feld wird anscheinend gar nicht mehr verwendet. Die Liste der Supervisoren steht nun in einer anderen Tabelle - es können auch mehrere sein.

**Comment by sschuppUOS** [comment]
Wurde schon gelöscht, bzw. es existiert mittlerweile kein Feld supervisor_id mehr in der Tabelle eportfolio
