### ISSUE TITLE
PHP-Warning

### ISSUE THREAD

**Issue by Davka** [elan-ev/ePortfolio#309]
`PHP message: PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/.../public/plugins_packages/virtUOS/EportfolioPlugin/views/showsupervisor/index.php on line 16"`

**Comment by tgloeggl** [comment]
PHP message: PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable in EportfolioPlugin/controllers/showsupervisor.php on line 51"
