### ISSUE TITLE
Activity Feed: Export aller Aktivitäten

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/ePortfolio#330]
CSV-Export aller Aktivitäten unter neuem Aktionspunkt beim Activity Feed:
* Export aller Aktivitäten als CSV

Der Export listet nach Personen gruppiert alle Aktivitäten für diese Person mit Datum.

Zu klären: Datenschutz

**Comment by SteffiBru** [comment]
Meeting Julia+Till+Steffi-Ergebnis (28.04.)
- Problem: Freigaben einmal erteilt zu V-Beginn: dann wird die Ampel grün und bleibt grün, auch wenn die Inhalte erst später zugefügt werden - wird selten genutzt werden (wollen / müssen) - Datenschutz...Studis müssen zustimmen? - Prüfungsrelevante Daten werden erhoben, daber müsste das gehen - wir fragen Datenschutzbeauftragte Schöndube - Kapitel sollen bearbeitbar bleiben auch nach der Deadline
