### ISSUE TITLE
Benachrichtigungen über Portfoliofreigaben

### ISSUE THREAD

**Issue by Davka** [elan-ev/ePortfolio#340]
Es wäre wünschenswert (Aussage vom Lehrenden), wenn man irgendwie einstellen könnte, von wem man eine Benachrichtigung erhalten möchte, wenn ein Portfolio freigegeben wurde. Aktuell ist es so, dass die Lehrenden dann 20 - 30 Benachrichtigungen erhalten und dann erstmal filtern müssen, was für sie wichtig ist.

**Comment by tgloeggl** [comment]
Lösung: Dozierende sollen im Portfolio-Arbeit Reiter die Benachrichtigungen für diese VA ausschalten können.

**Comment by sschuppUOS** [comment]
@tgloeggl Sind Benachrichtigungen noch erforderlich, wenn durch #275 einmal täglich ein Aktivitätsüberblick an die Supervisor verteilt wird?

**Comment by Davka** [comment]
Glaube nicht!

**Comment by SteffiBru** [comment]
Wir hatten gesagt, dass der tägliche Aktivitätsüberblick die Benachrichtungen ablöst/ ersetzt, da sonst ggf. sehr viele Benachrichtungen bei den Lehrenden eingehen (hatten wir im Testbetrieb schon so, da verliert man auch den Überblick). Also: Nein, Benachrichtigungen sind nicht mehr zusätzlich erforderlich.

________________________________
Von: Steffen <notifications@github.com>
Gesendet: Montag, 9. November 2020 15:46
An: elan-ev/ePortfolio
Cc: Brunner, Stefanie; Assign
Betreff: [Suspicious NEWSLETTER detected] Re: [elan-ev/ePortfolio] Benachrichtigungen über Portfoliofreigaben (#340)


@tgloeggl<https://github.com/tgloeggl> Sind Benachrichtigungen noch erforderlich, wenn durch #275<https://github.com/elan-ev/ePortfolio/issues/275> einmal täglich ein Aktivitätsüberblick an die Supervisor verteilt wird?
