### ISSUE TITLE
Freigaben kleinteiliger 

### ISSUE THREAD

**Issue by julianadinewarrelmann** [elan-ev/ePortfolio#353]
Ich würde mir wünschen, dass die Studierenden auch Unterkapitel und vielleicht sogar einzelne Abschnitte zur Ansicht für Lehrende freigeben können, statt nur ganze Kapitel.

**Comment by tgloeggl** [comment]
Kleinteiligere Freigaben:
* Übersicht/Ansicht: Bleiben jetzt bei der Übersicht der Hauptkapitel-Freigaben, weil das sonst zu viele Auswirkungen hätte auf andere Anzeigen und sehr viele nicht so eben mal lösbare Fragen aufwerfen würde (1/8 Freigaben bezieht sich auf Kapitel, bisher nicht mit Unterkapiteln vorgesehen)
* Die Darstellung ist trotzdem nun invertierte, aufgeteilt nach Portfolioberechtigten und einzelnen Nutzern.
