### ISSUE TITLE
SQL-Fehler

### ISSUE THREAD

**Issue by Davka** [elan-ev/ePortfolio#365]
`show/newportfolio?cid=cd0880c3a16a64ac4d3724dba951979c HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "studip.uni-vechta.de", referrer: "https://studip.uni-vechta.de/plugins.php/eportfolioplugin/show?cid=cd0880c3a16a64ac4d3724dba951979c"
2020/09/15 12:24:54 [error] 1593#1593: *7205292 FastCGI sent in stderr: "PHP message: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'eportfolio_id' in 'field list' in lib/classes/StudipPDOStatement.php:154
Stack trace:
#0 lib/classes/StudipPDOStatement.php(154): PDOStatement->execute()
#1 public/plugins_packages/virtUOS/EportfolioPlugin/controllers/show.php(206): StudipPDOStatement->execute(Array)
#2 vendor/trails/trails.php(557): ShowController->newportfolio_action()
#3 app/controllers/studip_controller.php(117): Trails_Controller->perform('newportfolio')
#4 vendor/trails/trails.php(154): StudipController->perform('newportfolio')
#5 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('show/newportfol...')
#6 lib/plugins/core/StudIPPlugin.class.php(161): Trails_Dispatcher->dispatch('show/newportfol...')`

**Comment by sschuppUOS** [comment]
Ich kann den SQL-Fehler nicht reproduzieren. Könnten Sie bitte eine genauere Erklärung liefern, wie sie diesen Fehler produziert haben.

**Comment by Davka** [comment]
https://github.com/elan-ev/ePortfolio/blob/master/migrations/018_update_permission_portfolios.php In der Migation wird die Spalte eportfolio_id gelöscht

https://github.com/elan-ev/ePortfolio/blob/master/controllers/show.php#L204

Hier wird aber noch versucht in diese Spalte zu schreiben, dadurch resultiert auch der Fehler
