### ISSUE TITLE
Lehrende automatisch in Berechtigtengruppe eintragen

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/ePortfolio#372]
Einmalig beim aktivieren des Plugins im Kurs die alle momentan vorhandenen Lehrenden in die Gruppe der Portfolioberechtigten eintragen.

**Comment by sschuppUOS** [comment]
Erste Version in 4a922d6ac128b51593024eabc7f0d8dd2ce19eca 
Lehrende werden aber dauerhaft hinzugefügt, nicht einmalig
