### ISSUE TITLE
Studierendensicht: Bereich "Übersicht" ist leer

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#383]
Als Studierende komme ich in meinem ePortfolio als erstes auf den Bereich "Übersicht". Hier erscheint üblicherweise je verteilter Vorlage ein Kasten mit den wichtigsten Infos zu der Vorlage (wieviel Prozent bearbeitet, wieviele Kapitel freigegeben, wieviele Notizen vorhanden). Diese Seite ist im Moment fälschlicherweise leer.

**Comment by Davka** [comment]
Du meintest, du weißt woran das liegen kann

**Comment by tgloeggl** [comment]
Lag am Fehler beim Verteilen einer Vorlage ( #384 ). Da das verteilen vorzeitig abgebrochen wurde, fehlte der Eintrag in der Datenbank und es wurde die Vorlage nicht auf der Übersichtsseite angezeigt.
