### ISSUE TITLE
Fehlermeldung beim Verteilen einer neuen Vorlage

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#384]
Wenn ich als Lehrende eine neu erstellte Vorlage an meine Studierenden verteile, erscheint eine rote Fehlermeldung: 
"Fehler! Bitte wenden Sie sich an Ihren Systemadministrator.

    Class 'Mooc\UI\Section\Errors\AccessDenied' not found"

Die Vorlage wird trotz Fehlermeldung verteilt, das sieht man, wenn man als Lehrende zurück in den Verwaltungsbereich geht (und die Studierenden sehen auch die neu verteilten Vorlagen). 

In einer weiteren neuen Vorlage habe ich lediglich ein Freitextfeld befüllt, hier kam beim VErteilen eine noch längere Fehlermeldung (ebenfalls rot, die Vorlage wurde ebenfalls korrekt verteilt, soweit ich das sehen kann):

"Houston, we've got a problem.
Typ: Error
Nachricht: Class 'Mooc\UI\Section\Errors\AccessDenied' not found
Code: 0
Stack trace:
#$ public/plugins_packages/virtUOS/Courseware/blocks/Section/Section.php(222)
#0 public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(211): Mooc\UI\Section\Section->set_icon_handler()
#1 public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(170): Mooc\Import\XmlImport->processSectionNode()
#2 public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(135): Mooc\Import\XmlImport->processSubChapterNode()
#3 public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(53): Mooc\Import\XmlImport->processChapterNode()
#4 public/plugins_packages/virtUOS/EportfolioPlugin/models/VorlagenCopy.class.php(57): Mooc\Import\XmlImport->import()
#5 public/plugins_packages/virtUOS/EportfolioPlugin/controllers/showsupervisor.php(107): VorlagenCopy::copyCourseware()
#6 vendor/trails/trails.php(557): ShowsupervisorController->createportfolio_action()
#7 app/controllers/studip_controller.php(129): Trails_Controller->perform()
#8 vendor/trails/trails.php(154): StudipController->perform()
#9 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response()
#10 lib/plugins/core/StudIPPlugin.class.php(161): Trails_Dispatcher->dispatch()
#11 public/plugins.php(54): StudIPPlugin->perform()
#12 {main}"

**Comment by tgloeggl** [comment]
Die Fehlerursache lag an der Courseware, siehe https://github.com/virtUOS/courseware/issues/244
