### ISSUE TITLE
Automatische Eintragung der Lehrenden in die Berechtigtengruppe

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#386]
Laut Till sollte der Mechanismus folgendermaßen funktionieren, was er aber nicht tut: 

Sobald ich als Lehrende über "mehr" das Portfolio-Plugin aktiviere, werden automatisch alle in der Veranstaltung eingetragenen Lehrenden (also die mit der Rolle Lehrende) in die Berechtigtengruppe fürs Portfolio eingetragen (im Lehrendenbereich links im Menü über "Berechtigungen Portfolioarbeit" aufrufbar). 

Im Moment bleibt die Berechtigtengruppe leer, trotz Aktivierung des Plugins in der Veranstaltung.

**Comment by tgloeggl** [comment]
#372

**Comment by Davka** [comment]
Das Problem lag am Stud.IP Kern
