### ISSUE TITLE
Lehrende sollen bei der Freigabe nur Lese-, keine Schreibrechte in Studierendenportfolios bekommen 

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#388]
Nur, wenn über die Courseware-Funktion dies ausdrücklich eingestellt wird, sollten Lehrende auch Schreibrechte in den Portfolios der Studierenden bekommen. 

Wenn ein Studi über die Zugriffsrechte-Seite mit einem Klick Lehrenden Freigaben erteilt, erhalten Lehrende im Moment fälschlicherweise auch Schreibrechte im Portfolio der Studierenden. Sie sollen jedoch lediglich in den speziellen Feedback-Blöcken schreiben können und NICHT automatisch rechts oben den Umschaltknopf für den Bearbeitungsmodus sehen.

**Comment by tgloeggl** [comment]
Das konnte ich nicht reproduzieren, in all meinen Tests haben die Lehrenden nur Leserechte am Portfolio (sofern nicht anders eingestellt). Entweder war das noch ein Fehler in der Courseware, der mittlerweile behoben ist, oder es waren ebenfalls Auswirkungen von #384
