### ISSUE TITLE
Einzelfreigabe durch Studierende

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#389]
Die Einzelfreigabe (= zusätzliche Freigabe an Einzelpersonen durch Studierende) hat funktioniert, jedoch nach einem Aus- und erneutem Einloggen der Studierenden ist die Einzelperson in der Anzeige der Zugriffsberechtigten verschwunden. Das Recht, das Portfolio einzusehen, blieb jedoch bei der Lehrenden bestehen.

**Comment by Davka** [comment]
Das sollte ja nach deiner Meinung nach gehen. Kannst du das prüfen?

**Comment by tgloeggl** [comment]
Habe es überprüft und konnte keine Probleme feststellen. Vllt. ebenfalls noch Nachwirkungen von #384?
