### ISSUE TITLE
Verteilen einer Vorlage - es kommt nicht alles bei den Studis an

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#392]
Beim Verteilen einer Vorlage wird nur das erste Kapitel und das erste Unterkapitel verteilt. Weitere Kapitel und Unterkapitel kommen bei den Studierenden nicht an. 

Beispiel: In der Vorlage gibt es drei Kapitel mit jeweils zwei Unterkapiteln. Bei der Studierenden wird nur das erste Kapitel plus ein Unterkapitel darin angezeigt. Das zweite Unterkapitel sowie Kapitel 2 und 3 fehlen komplett.

**Comment by Davka** [comment]
Das Problem bestand scheinbar darin, dass die "Supervisoren" (oder so) immer als Autor in das Portfolio eingetragen wurden. Dadurch resultierten auch die AccessDenied - Exception beim verteilen, weil der Supervisor (oder so) keine Rechte an der VA hatte, diese zu ändern.
