### ISSUE TITLE
Fehlermeldung bei Verteilen einer Vorlage

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#393]
Als Dozentin habe ich eine Vorlage erstellt, drei Kapitel mit je zwei Unterkapiteln. Beim Verteilen dieser Vorlage erscheint folgende Fehlermeldung: 
![grafik](https://user-images.githubusercontent.com/58294058/113705047-3e2ce300-96dd-11eb-8171-02684336efd0.png)

Anschließend kann die Studierende von der verteilten Vorlage das erste Kapitel und darin das erste Unterkapitel sehen. Das zweite Unterkapitel und die beiden weiteren Kapitel werden der Studentin nicht angezeigt.

**Comment by Davka** [comment]
082e698b9888525e6a8d36e28c608a08524a65ea
