### ISSUE TITLE
Anzeigefehler in Übersicht in Studierendenportfolio

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#394]
Im Bereich "Übersicht" (=Reiter "Übersicht") im Studierendenportfolio wird eigentlich je verteilter Vorlage ein Kästchen mit den Angaben zu der jeweiligen Vorlage angezeigt. 

In der aktuellen Veranstaltung, in der ich mich als Studierende jetzt befinde, wurden bereits 3 Vorlagen verteilt. Nach dem Verteilen der dritten Vorlage erscheint nur ein Kästchen mit den drei Kapiteln dieser dritten Vorlage. Wenn ich das Portfolio aufrufe, sehe ich als Studierende jedoch: 
- das erste Kapitel der ersten verteilten Vorlage
- das erste Kapitel der zweiten verteilten Vorlage und 
- das erste Kapitel der dritten verteilten Vorlage. 

Hier das Übersichtskästchen: 
![grafik](https://user-images.githubusercontent.com/58294058/113705484-c4e1c000-96dd-11eb-8f84-f6f9488902b9.png)

Und hier das Menü, das ich sehe, wenn ich ins ePortfolio wechsele: 
![grafik](https://user-images.githubusercontent.com/58294058/113705608-ee025080-96dd-11eb-8331-c05def52e4a3.png)

Die dritte Vorlage hatte drei Kapitel: 
1) Kapitel 1 -Montag
2) Kapitel 2 - Dienstag
3) Kapitel 3 - Mittwoch

Davon ist nur das erste Kapitel sichtbar. Die anderen "Kapitel 1" kommen aus den Vorlagen Nr. 1 und Nr. 2.

**Comment by Davka** [comment]
sollte mit 082e698b9888525e6a8d36e28c608a08524a65ea auch behoben sein
