### ISSUE TITLE
Courseware/eKEP: Zugriffsberechtigungen in Lehrendensicht fehlerhaft

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#395]
Beispiel: Eine Studierende hat zwei Vorlage verteilt bekommen mit insgesamt 7 Kapiteln. Davon hat sie jetzt die ersten drei freigegeben. Die Dozentin kann jedoch alle sieben Kapitel sehen: wenn sie das Studierendenkästchen anklickt und wenn sie das Portfolio der Studierenden aufruft. Das soll sie natürlich nicht.

**Comment by Davka** [comment]
Das sollte nun funktionieren
