### ISSUE TITLE
Lehrendensicht: Anzeige auf Studierendenkästchen fehlerhaft

### ISSUE THREAD

**Issue by SteffiBru** [elan-ev/ePortfolio#398]
Auf dem Studierendenkästchen in der Lehrendenansicht (unter den Tabellen mit den verteilten und erstellten Vorlagen) wird die Anzahl der freigegebenen Kapitel angezeigt. Obwohl die Studierende zwei Kapitel freigegeben hat, steht hier "0 von 6"

![grafik](https://user-images.githubusercontent.com/58294058/114016756-76fac280-986b-11eb-84a2-77637e749a0f.png)

**Comment by Davka** [comment]
Sollte nun auch korrekt sein
